**(2 points)** Given a vector **a** and a set of vectors $$X = x_1, \ldots, x_m$$, we say that $x_i$ is the nearest neighbor of **a** if it’s the closest vector to **a** from the $set(X)$. In ML, the idea of the nearest neighbor and its generalization, k-nearest neighbors, is used for solving classification and regression problems (see k-nearest neighbors algorithm).

Find the nearest neighbor of

$$
\mathbf{a} = \begin{bmatrix} 3 \\ 1 \\ 4 \end{bmatrix}
$$

from the set of vectors \( x_1, \ldots, x_4 \) below:

$$
x_1 = \begin{bmatrix} 4 \\ 3 \\ 6 \end{bmatrix}, \quad
x_2 = \begin{bmatrix} 3 \\ 1 \\ 9 \end{bmatrix}, \quad
x_3 = \begin{bmatrix} 1 \\ 4 \\ 10 \end{bmatrix}, \quad
x_4 = \begin{bmatrix} 3 \\ 4 \\ 0 \end{bmatrix}
$$

If there is more than one nearest neighbor, mark all of them.


## a) Euclidean distance

In [1]:
import numpy as np

In [3]:
a = np.array([3,1,4])
x1 = np.array([4,3,6])
x2 = np.array([3,1,9])
x3 = np.array([1,4,10])
x4 = np.array([3,4,0])

In [4]:
def find_distance(a,x):
    distance = np.sqrt(np.sum(np.square(a-x)))
    return distance

d1 = find_distance(a,x1)
d2 = find_distance(a,x2)
d3 = find_distance(a,x3)
d4 = find_distance(a,x4)

print(d1,d2,d3,d4)
if d1 == min(d1,d2,d3,d4):
    print("x1 is the nearest point")
elif d2 == min(d1,d2,d3,d4):
    print("x2 is the nearest point")
elif d3 == min(d1,d2,d3,d4):
    print("x3 is the nearest point")
else:
    print("x4 is the nearest point")

3.0 5.0 7.0 5.0
x1 is the nearest point


## b) Cosine similarity

In [12]:
def cosine_similarity(a,x):
    similarty =  np.dot(a,x) / (np.linalg.norm(a) * np.linalg.norm(x))
    return similarty

s1 = cosine_similarity(a,x1)
s2 = cosine_similarity(a,x2)
s3 = cosine_similarity(a,x3)
s4 = cosine_similarity(a,x4)
print(s1,s2,s3,s4)
if s1  == max(s1,s2,s3,s4):
    print('x1 is the nearest point')
elif s2 == max(s1,s2,s3,s4):
    print('x2 is the nearest point')
elif s3 == max(s1,s2,s3,s4):
    print('x3 is the nearest point')
else:
    print('x4 is the nearest point')

0.9792938238560597 0.9456936252285787 0.8521543260453266 0.5099019513592785
x1 is the nearest point


**2. (2 points)** Consider a linear classifier with the following separating hyperplane:

$$
x_1 + x_2 − x_3 + x_4 − x_5 = 2
$$

According to this classifier, which class labels will be assigned to the examples (a) - (e)?

| Example | $x_1$  | $x_2$ | $x_3$ | $x_4$ | $x_5$ |
| ------- | --------- | --------- | --------- | --------- | --------- |
| **a**   | 1         | 0         | 1         | 0         | 0         |
| **b**   | 0         | 1         | 1         | 0         | 1         |
| **c**   | 1         | 1         | 1         | 1         | 1         |
| **d**   | 2         | 0         | 1         | 0         | 1         |
| **e**   | 2         | 2         | 0         | 0         | 0         |


In [17]:
def fitting(x1,x2,x3,x4,x5):
    result = x1 + x2 - x3 + x4 - x5
    if result > 2:
        return 1
    else:
        return 0

In [19]:
#According to this classifier, which class labels will be assigned to the examples (a) - (e)?
data_set = {
    'a' : [1,0,1,0,0],
    'b' : [0,1,1,0,1],
    'c' : [1,1,1,1,1],
    'd' : [2,0,1,0,1],
    'e' : [2,2,0,0,0]
}

for labels,items in data_set.items():
    if fitting(items[0],items[1],items[2],items[3],items[4]) == 1:
        print(f'{labels} belongs to postive class')
    else:
        print(f'{labels} belongs to negative class')

a belongs to negative class
b belongs to negative class
c belongs to negative class
d belongs to negative class
e belongs to postive class


**3. (3 points)** During the lectures, we discussed the concept of linear (in)dependence and saw examples of linearly (in)dependent sets of vectors.
A general way to check linear independence of a given set of vectors is to combine those vectors in a matrix and bring it to reduced row echelon form (RREF) with the help of elementary row operations.
If you are not yet familiar with this procedure, you can learn more about bringing a matrix to its RREF in this video. There is also another video that demonstrates how we can test a set of vectors for linear independence.
Once you are ready, you can solve the questions in this section.

**(a) (1 point)** Consider vectors $$v_1, v_2, v_3 , v_4$$ defined below:

$$
v_1 = \begin{bmatrix} 0 \\ 1 \\ 1 \\ 1 \end{bmatrix}, \quad 
v_2 = \begin{bmatrix} 1 \\ 2 \\ 0 \\ 3 \end{bmatrix}, \quad 
v_3 = \begin{bmatrix} 2 \\ 4 \\ 1 \\ 3 \end{bmatrix}, \quad 
v_4 = \begin{bmatrix} 1 \\ 2 \\ 1 \\ 0 \end{bmatrix}
$$

What is the dimensionality of the subspace $$V = span\{v_1, v_2, v_3 , v_4\}$$ spanned by these vectors?


### RREF using algorithms

In [10]:
def rref(matrix):
    l = 0
    rows, cols = matrix.shape
    for r in range(rows):
        if l >= cols:
            return matrix
        i = r
        while matrix[i][l] == 0:
            i += 1
            if i == rows:
                i = r
                l += 1
                if cols == l:
                    return matrix
        matrix[i], matrix[r] = matrix[r], matrix[i].copy()
        lv = matrix[r][l]
        matrix[r] = matrix[r] / lv
        for i in range(rows):
            if i != r:
                lv = matrix[i][l]
                matrix[i] = matrix[i] - lv * matrix[r]
        l += 1
    return matrix


matrix = np.array([[0,1,2,1],[1,2,4,2],[1,0,1,1],[1,3,3,0]], dtype=float)
result = rref(matrix)
print(result)

pivot_count = 0
for row in result:
    if any(row != 0):  
        pivot_count += 1

print(f"The dimensionality of the subspace V is: {pivot_count}")


[[ 1.  0.  0.  0.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0.  0.]]
The dimensionality of the subspace V is: 3


### RREF using build-in libraries (sympy) 


In [16]:
from sympy import Matrix

m = Matrix([[0,1,2,1],[1,2,4,2],[1,0,1,1],[1,3,3,0]])
rref_matrix, pivot_columns = m.rref()

num_pivot_columns = len(pivot_columns)
print(f"The dimensionality of the subspace V is: {num_pivot_columns}")
rref_matrix

The dimensionality of the subspace V is: 3


Matrix([
[1, 0, 0,  0],
[0, 1, 0, -1],
[0, 0, 1,  1],
[0, 0, 0,  0]])

**4. (3 points)** Consider two sets of vectors, $B$ and $S$:

$$
B = \left\{ b_1 = \begin{bmatrix} 1 \\ 2 \\ 1 \end{bmatrix}, \quad
            b_2 = \begin{bmatrix} 2 \\ 3 \\ 3 \end{bmatrix}, \quad
            b_3 = \begin{bmatrix} 3 \\ 8 \\ 2 \end{bmatrix} \right\}
$$

$$
S = \left\{ s_1 = \begin{bmatrix} 3 \\ 5 \\ 8 \end{bmatrix}, \quad
            s_2 = \begin{bmatrix} 5 \\ 14 \\ 13 \end{bmatrix}, \quad
            s_3 = \begin{bmatrix} 1 \\ 9 \\ 2 \end{bmatrix} \right\}
$$

Both $S$ and $B$  form valid bases in ${R}^3$. Find a transition matrix $A_{B \rightarrow S}$ from basis $B$ to basis $S$.


In [18]:
m = Matrix([
    [3 , 5 , 1 , 1 , 2 , 3],
    [5 , 14 , 9 , 2 , 3 , 8], 
    [8 , 13 , 2 , 1 , 3 , 2]
])
result,pivot_columns = m.rref()
result

Matrix([
[1, 0, 0, 13,  19, 181/4],
[0, 1, 0, -9, -13, -63/2],
[0, 0, 1,  7,  10,  99/4]])

In [21]:
print("Transition Matrix:")
result[:,3:]

Transition Matrix:


Matrix([
[13,  19, 181/4],
[-9, -13, -63/2],
[ 7,  10,  99/4]])